(autothemer-deftheme my-theme
		     "My theme based on tokyonight-storm"
		     ((((class color) (min-colors #xFFFFFF))
		       ((class color) (min-colors #xFF)))
		      (bg           "#24283b")
		      (bg-dark      "#1f2335")
		      (bg-dark1     "#1b1e2d")
		      (bg-highlight "#292e42")
		      (blue1        "#7aa2f7")
		      (blue2        "#3d59a1")
		      (blue3        "#2ac3de")
		      (blue4        "#0db9d7")
		      (blue5        "#89ddff")
		      (blue6        "#b4f9f8")
		      (blue7        "#394b70")
		      (comment      "#565f89")
		      (cyan         "#7dcfff")
		      (dark1        "#545c7e")
		      (dark2        "#737aa2")
		      (fg           "#c0caf5")
		      (fg-dark      "#a9b1d6")
		      (fg-gutter    "#3b4261")
		      (green1       "#9ece6a")
		      (green2       "#73daca")
		      (green3       "#41a6b5")
		      (magenta1     "#bb9af7")
		      (magenta2     "#ff007c")
		      (orange       "#ff9e64")
		      (purple       "#9d7cd8")
		      (red1         "#f7768e")
		      (red2         "#db4b4b")
		      (terminal     "#414868")
		      (yellow       "#e0af68"))

		     ;; face defaults
		     ((default      (:foreground blue1 :background bg))
		      (bold         (:weight 'bold))
		      (italic       (:slant 'italic))
		      (bold-italic  (:weight 'bold :slant 'italic))
		      (underline    (:underline t :foreground cyan))
		      (shadow       (:forground bg-highlight))
		      (link         (:foreground blue6 :underline t))
		      (link-visited (:foreground blue7 :underline t))
		      (error        (:foreground red2 :underline (:color red1 :style 'wave)))
		      (warning      (:foreground yellow :underline (:color red1 :style 'wave)))
		      (success      (:foreground green1))

		      ;; general faces
		      (cursor                     (:background bg))
		      (compilation-mode-line-exit (:inherit 'compilation-info :weight 'bold))
		      (coplitation-mode-line-fail (:inherit 'compilation-info :weight 'bold))
		      (fringe                     (:background bg))
		      (flyspell-incorrect         (:underline (:color orange :style 'wave)))
		      (flyspell-duplicate         (:underline (:color red1 :style 'wave)))
		      (header-line                (:background fg-dark :box (:line-width -1)))
		      (highlight                  (:background cyan))
		      (hl-line                    (:background cyan))
		      (isearch                    (:background green2 :weight 'italic))
		      (isearch-fail               (:foreground red1 :weight 'bold))
		      (lazy-highlight             (:weight 'italic))
		      (line-number                (:foreground fg-gutter))
		      (tty-menu-disabled-face     (:foreground magenta1 :background magenta2))
		      (tty-menu-enabled-face      (:background purple))
		      (tty-menu-selected-face     (:foreground yellow :background terminal :weight 'bold))
		      (minibuffer-prompt          (:background fg-dark :weight 'bold))
		      (mode-line                  (:foreground fg :background bg-dark :box (:line-width 1)))
		      (mode-line-inactive         (:foreground shadow :background dark2))
		      (mode-line-highlight        (:foreground magenta1 :background dark2))
		      (mode-line-buffer-id        (:inherit 'mode-line-emphasis))
		      (mode-line-emphasis         (:weight 'bold))
		      (region                     (:background cyan :extend nil))
		      (show-paren-match           (:background magenta1))
		      (show-paren-mismatch        (:background red1))

		      ;; font-lock-faces
		      (font-lock-doc-face          (:family Noto-Serif-Light-Italic :foreground fg-gutter :weight 'italic))
		      (font-lock-keyword-face      (:family NovaMono :forground fg :weight 'italic))
		      (font-lock-constant-face     (:family Advent-Pro-Bold :foreground fg-dark :weight 'bold))
		      (font-lock-type-face         (:family Abel-Regular :foreground cyan :weight 'italic))
		      (font-lock-regexp-face       (:family ABee-Italic :foreground yellow))
		      (font-lock-number-face       (:family Aleo :foreground purple))
		      (font-lock-string-face       (:family Amiri-Regular :foreground fg))
		      (font-lock-builtin-face      (:family NovaMono :foreground fg :weight 'bold))
		      (font-lock-comment-face      (:family Noto-Serif-Light-Italic :foreground fg-gutter :weight 'italic))
		      (font-lock-operator-face     (:family NovaMono :foreground fg :weight 'italic))
		      (font-lock-property-use-face (:family NovaMono :foreground fg :weight 'italic))
		      (font-lock-variable-use-face (:family NovaMono :foregroun fg))
		      (font-lock-function-call-face (:family NovaMono :foreground fg :weight 'bold))
		      (font-lock-function-name-face (:family NovaMono :foreground fg))
		      (font-lock-property-name-face (:family ))))
(provide 'my-theme)

