;; TODO: adjust faces for rainbow-delimeters
 (autothemer-deftheme my
		      "My theme based on tokyonight-storm"
		      ((((class color) (min-colors #xFFFFFF))
			((class color) (min-colors #xFF)))
		       (bg                    "#24283b")
		       (bg-dark         "#1f2335")
		       (bg-dark1        "#1b1e2d")
		       (bg-highlight    "#292e42")
		       (blue1           "#7aa2f7")
		       (blue2           "#3d59a1")
		       (blue3           "#2ac3de")
		       (blue4           "#0db9d7")
		       (blue5           "#89ddff")
		       (blue6           "#b4f9f8")
		       (blue7           "#394b70")
		       (comment         "#565f89")
		       (cyan            "#7dcfff")
		       (dark1           "#545c7e")
		       (dark2           "#737aa2")
		       (fg              "#c0caf5")
		       (fg-dark         "#a9b1d6")
		       (fg-gutter       "#3b4261")
		       (green1          "#9ece6a")
		       (green2          "#73daca")
		       (green3          "#41a6b5")
		       (magenta1        "#bb9af7")
		       (magenta2        "#ff007c")
		       (orange          "#ff9e64")
		       (purple          "#9d7cd8")
		       (red1            "#f7768e")
		       (red2            "#db4b4b")
		       (terminal        "#414868")
		       (yellow          "#e0af68"))

		      ;; face defaults
		      ((default         (:family "CutiveMono":foreground fg :background bg :height 160))
		       (fixed-pitch     (:family "NovaMono" :foreground fg :height 160))
		       (bold            (:weight 'bold))
		       (italic          (:slant 'italic))
		       (bold-italic     (:weight 'bold :slant 'italic))
		       (underline       (:underline t :foreground cyan))
		       (link            (:foreground blue6 :underline t))
		       (link-visited    (:foreground blue7 :underline t))
		       (error           (:foreground red2 :underline (:color red1 :style 'wave)))
		       (warning         (:foreground yellow :underline (:color red1 :style 'wave)))
		       (success         (:foreground green1))

		       ;; general faces
		       (cursor                        (:background bg-dark1))
		       (compilation-mode-line-exit    (:inherit 'compilation-info :weight 'bold))
		       (coplitation-mode-line-fail    (:inherit 'compilation-info :weight 'bold))
		       (fringe                        (:background bg))
		       (flyspell-incorrect            (:underline (:color orange :style 'wave)))
		       (flyspell-duplicate            (:underline (:color red1 :style 'wave)))
		       (header-line                   (:background fg-dark :box (:line-width -1)))
		       (highlight                     (:foreground cyan :background bg-highlight))
		       (hl-line                       (:foreground cyan :background bg-highlight))
		       (isearch                       (:background green2 :slant 'italic))
		       (isearch-fail                  (:foreground red1 :weight 'bold))
		       (lazy-highlight                (:slant 'italic))
		       (line-number                   (:foreground fg-gutter))
		       (tty-menu-disabled-face        (:foreground magenta1 :background magenta2))
		       (tty-menu-enabled-face         (:background purple))
		       (tty-menu-selected-face        (:foreground yellow :background terminal :weight 'bold))
		       (minibuffer-prompt             (:foreground fg :background bg-dark :weight 'bold))
		       (mode-line                     (:foreground fg :background bg-dark :box (:line-width 1)))
		       (mode-line-inactive            (:foreground fg-gutter :background dark2))
		       (mode-line-highlight           (:foreground magenta1 :background dark2))
		       (mode-line-buffer-id           (:inherit 'mode-line-emphasis))
		       (mode-line-emphasis            (:weight 'bold))
		       (region                        (:background cyan :extend nil))
		       (show-paren-match              (:background magenta1))
		       (show-paren-mismatch           (:background red1))

		       ;; font-lock-faces
		       (font-lock-doc-face                     (:family "Noto-Serif" :foreground fg-gutter :slant 'italic))
		       (font-lock-keyword-face                 (:family "Share-Tech-Mono" :foreground green2 :slant 'italic :height 160))
		       (font-lock-constant-face                (:family "Share-Tech-Mono" :foreground green1 :weight 'bold :height 160))
		       (font-lock-type-face                    (:family "Share-Tech-Mono" :foreground green3 :slant 'italic :height 160))
		       (font-lock-regexp-face                  (:family "NovaMono" :foreground fg-dark :background cyan :height 160))
		       (font-lock-number-face                  (:family "NovaMono" :foreground fg :height 160))
		       (font-lock-string-face                  (:family "Share-Tech-Mono" :foreground fg-dark :slant 'italic :height 160))
		       (font-lock-builtin-face                 (:family "NovaMono" :foreground magenta1 :height 160))
		       (font-lock-comment-face                 (:family "Noto-Serif" :foreground fg-gutter :slant 'italic :height 160))
		       (font-lock-operator-face                (:family "NovaMono" :foreground fg :height 160))
		       (font-lock-property-use-face            (:family "NovaMono" :foreground orange :height 160))
		       (font-lock-variable-use-face            (:family "NovaMono" :foreground orange :height 160))
		       (font-lock-function-call-face           (:family "NovaMono" :foreground orange :height 160))
		       (font-lock-function-name-face           (:family "Share-Tech-Mono" :foreground purple :weight 'bold :height 160))
		       (font-lock-property-name-face           (:family "Share-Tech-Mono" :foreground purple :weight 'bold :height 160))
		       (font-lock-variable-name-face           (:family "Share-Tech-Mono" :foreground purple :weight 'bold :height 160))
		       (font-lock-misc-punctuation-face        (:family "NovaMono" :foreground fg :height 160))
		       (font-lock-comment-delimiter-face       (:family "Noto-Serif" :foreground fg-gutter :height 160))
		       (font-lock-regexp-grouping-backslash    (:family "NovaMono" :foreground fg-dark :height 160))
		      (font-lock-regexp-grouping-construct     (:family "NovaMono" :foreground fg-dark :height 160))

		       ;; org-mode-faces
		       (org-table                (:family "NovaMono" :foreground fg :height 160))
		       (org-tag                  (:family "Noto-Serif" :foreground fg-gutter :background orange :weight 'bold :height 160))
		       (org-cite                 (:family "Noto-Serif" :foreground terminal  :slant 'italic :height 160))
		       (org-code                 (:family "NovaMono" :foreground fg :height 160))
		       (org-date                 (:family "NovaMono" :foreground fg-gutter :background yellow :height 160))
		       (org-done                 (:family "Noto-Serif" :foreground fg-gutter :background green1 :height 160)
		       (org-link                 (:family "NovaMono" :foreground blue1 :underline (:color blue1 :style 'straight)))
		       (org-todo                 (:family "Noto-Serif" :foreground fg-gutter :background orange :height 160))
		       (org-block                (:family "Alumni-Serif-Pinstripe" :foreground fg-dark) :height 100)
		       (org-macro                (:family "NovaMono" :foreground fg :height 100))
		       (org-quote                (:family "Alumni-Serif-Pinstripe" :foreground blue2 :slant 'italic :height 160))
		       (org-verse                (:family "Alumni-Serif-Pinstripe" :foreground blue2 :slant 'italic :height 160))
		       (org-default              (:family "Noto-Serif" :foreground fg :size 16))
		       (org-level-1              (:family "Alumni-Serif-Pinstripe" :foregroun blue1 :weight 'bold :height 200))
		       (org-level-2              (:family "Alumni-Serif-Pinstripe" :foreground blue2 :weight 'bold :height 180))
		       (org-level-3              (:family "Alumni-Serif-Pinstripe" :foreground blue3 :weight 'bold :height 160))
		       (org-level-4              (:family "Alumni-Serif-Pinstripe" :foreground blue4 :weight 'bold :height 140))
		       (org-level-5              (:family "Alumni-Serif-Pinstripe" :foreground blue5 :weight 'bold :height 120))
		       (org-level-6              (:family "Alumni-Serif-Pinstripe" :foreground blue6 :weight 'bold :height 100))
		       (org-level-7              (:family "Alumni-Serif-Pinstripe" :foreground blue7 :weight 'bold :height 100))
		       (org-list-dt              (:family "Noto-Serif" :foreground fg-dark :height 160))
		       (org-checkbox             (:family "Alumni-Serif-Pinstripe":foreground fg-gutter :height 160))
		       (org-column-title         (:family "Share-Tech-Mono" :foreground fg :weight 'bold :height 160))
		       (org-table-header         (:family "Share-Tech-Mono" :foreground fg :weight 'bold :height 160))
		       (org-document-info        (:family "Alumni-Serif-Pinstripe" :foreground comment :slant 'italic :height 160))
		       (org-block-begin-line     (:family "NovaMono" :foreground comment :height 100))
		       (org-modern-block-name    (:family "NovaMono" :foreground comment :height 100)))))

 (provide-theme 'my)

