;; TODO: add font sizes
;; TODO: adjust faces for rainbow-delimeters
;; TODO: find alternate default font that is mono spaced
;; TODO: change colors and fonts for some of the font-lock faces
;; TODO: change cursor foreground color to have a high contrast
 (autothemer-deftheme my
		      "My theme based on tokyonight-storm"
		      ((((class color) (min-colors #xFFFFFF))
			((class color) (min-colors #xFF)))
		       (bg           "#24283b")
		       (bg-dark      "#1f2335")
		       (bg-dark1     "#1b1e2d")
		       (bg-highlight "#292e42")
		       (blue1        "#7aa2f7")
		       (blue2        "#3d59a1")
		       (blue3        "#2ac3de")
		       (blue4        "#0db9d7")
		       (blue5        "#89ddff")
		       (blue6        "#b4f9f8")
		       (blue7        "#394b70")
		       (comment      "#565f89")
		       (cyan         "#7dcfff")
		       (dark1        "#545c7e")
		       (dark2        "#737aa2")
		       (fg           "#c0caf5")
		       (fg-dark      "#a9b1d6")
		       (fg-gutter    "#3b4261")
		       (green1       "#9ece6a")
		       (green2       "#73daca")
		       (green3       "#41a6b5")
		       (magenta1     "#bb9af7")
		       (magenta2     "#ff007c")
		       (orange       "#ff9e64")
		       (purple       "#9d7cd8")
		       (red1         "#f7768e")
		       (red2         "#db4b4b")
		       (terminal     "#414868")
		       (yellow       "#e0af68"))

		      ;; face defaults
		      ((default         (:family "NovaMono":foreground fg :background bg))
		       (fixed-pitch     (:family "NovaMono" :foreground fg))
		       (bold            (:weight 'bold))
		       (italic          (:slant 'italic))
		       (bold-italic     (:weight 'bold :slant 'italic))
		       (underline       (:underline t :foreground cyan))
		       (link            (:foreground blue6 :underline t))
		       (link-visited    (:foreground blue7 :underline t))
		       (error           (:foreground red2 :underline (:color red1 :style 'wave)))
		       (warning         (:foreground yellow :underline (:color red1 :style 'wave)))
		       (success         (:foreground green1))

		       ;; general faces
		       (cursor                        (:background bg))
		       (compilation-mode-line-exit    (:inherit 'compilation-info :weight 'bold))
		       (coplitation-mode-line-fail    (:inherit 'compilation-info :weight 'bold))
		       (fringe                        (:background bg))
		       (flyspell-incorrect            (:underline (:color orange :style 'wave)))
		       (flyspell-duplicate            (:underline (:color red1 :style 'wave)))
		       (header-line                   (:background fg-dark :box (:line-width -1)))
		       (highlight                     (:background cyan))
		       (hl-line                       (:background cyan))
		       (isearch                       (:background green2 :weight 'italic))
		       (isearch-fail                  (:foreground red1 :weight 'bold))
		       (lazy-highlight                (:weight 'italic))
		       (line-number                   (:foreground fg-gutter))
		       (tty-menu-disabled-face        (:foreground magenta1 :background magenta2))
		       (tty-menu-enabled-face         (:background purple))
		       (tty-menu-selected-face        (:foreground yellow :background terminal :weight 'bold))
		       (minibuffer-prompt             (:background fg-dark :weight 'bold))
		       (mode-line                     (:foreground fg :background bg-dark :box (:line-width 1)))
		       (mode-line-inactive            (:foreground fg-gutter :background dark2))
		       (mode-line-highlight           (:foreground magenta1 :background dark2))
		       (mode-line-buffer-id           (:inherit 'mode-line-emphasis))
		       (mode-line-emphasis            (:weight 'bold))
		       (region                        (:background cyan :extend nil))
		       (show-paren-match              (:background magenta1))
		       (show-paren-mismatch           (:background red1))

		       ;; font-lock-faces
		       (font-lock-doc-face                     (:family "NovaMono" :foreground fg-gutter :weight 'italic))
		       (font-lock-keyword-face                 (:family "NovaMono" :forground fg :weight 'italic))
		       (font-lock-constant-face                (:family "NovaMono" :foreground fg-dark :weight 'bold))
		       (font-lock-type-face                    (:family "NovaMono" :foreground cyan :weight 'italic))
		       (font-lock-regexp-face                  (:family "NovaMono" :foreground yellow))
		       (font-lock-number-face                  (:family "NovaMono" :foreground purple))
		       (font-lock-string-face                  (:family "NovaMono" :foreground fg))
		       (font-lock-builtin-face                 (:family "NovaMono" :foreground fg :weight 'bold))
		       (font-lock-comment-face                 (:family "NovaMono" :foreground fg-gutter :weight 'italic))
		       (font-lock-operator-face                (:family "NovaMono" :foreground fg :weight 'italic))
		       (font-lock-property-use-face            (:family "NovaMono" :foreground fg :weight 'italic))
		       (font-lock-variable-use-face            (:family "NovaMono" :foregroun fg))
		       (font-lock-function-call-face           (:family "NovaMono" :foreground fg :weight 'bold))
		       (font-lock-function-name-face           (:family "NovaMono" :foreground fg))
		       (font-lock-property-name-face           (:family "NovaMono" :foreground fg))
		       (font-lock-variable-name-face           (:family "NovaMono" :forground fg :weight 'italic))
		       (font-lock-misc-punctuation-face        (:family "NovaMono" :foreground fg))
		       (font-lock-comment-delimiter-face       (:family "NovaMono" :foreground fg-gutter :weight 'italic))
		       (font-lock-regexp-grouping-backslash    (:family "NovaMono" :forground cyan :weight 'italic))
		       (font-lock-regexp-grouping-construct    (:family "NovaMono" :foreground cyan :weight 'italic))

		       ;; org-mode-faces
		       (org-table                (:family "NovaMono" :forground fg))
		       (org-tag                  (:family "Noto-Serif-Light-Italic" :foreground fg-dark :background orange :weight 'bold))
		       (org-cite                 (:family "Amiri-Regular" :forground fg-dark :weight 'italic))
		       (org-code                 (:family "NovaMono" :foreground fg))
		       (org-date                 (:family "NovaMono" :foreground fg-gutter :background yellow))
		       (org-done                 (:family "Noto-Serif-Light-Italic" :foreground blue6 :background green1))
		       (org-link                 (:family "Noto-Serif-Light-Italic" :foreground blue1 :underline (:color blue1 :style 'straight)))
		       (org-todo                 (:family "Noto-Serif-Light-Italic" :foreground blue6 :background orange))
		       (org-block                (:family "NovaMono" :foreground fg))
		       (org-macro                (:family "NovaMono" :forground fg))
		       (org-quote                (:family "Amiri-Regular" :foreground blue2 :weight 'italic))
		       (org-verse                (:family "Amiri-Regular" :foreground blue2 :weight 'italic))
		       (org-default              (:family "Amiri-Regular" :foreground fg))
		       (org-level-1              (:family "Amiri-Regular" :foregroun blue1 :weight 'bold))
		       (org-level-2              (:family "Amiri-Regular" :foreground blue2 :weight 'bold))
		       (org-level-3              (:family "Amiri-Regular" :fourground blue3 :weight 'bold))
		       (org-level-4              (:family "Amiri-Regular" :foreground blue4 :weight 'bold))
		       (org-level-5              (:family "AmiriRegular" :foreground blue5 :weight 'bold))
		       (org-level-6              (:family "Amiri-Regular" :foreground blue6 :weight 'bold))
		       (org-level-7              (:family "Amiri-Regular" :foreground blue7 :weight 'bold))
		       (org-list-dt              (:family "Noto-Serif-Light-Italic" :foreground fg-dark))
		       (org-checkbox             (:foreground fg-gutter :weight 'bold))
		       (org-column-title         (:family "NovaMono" :foreground fg :weight 'bold))
		       (org-table-header         (:family "NovaMono" :foreground fg :weight 'bold))
		       (org-document-info        (:family "Amiri-Regular" :foreground comment :weight 'bold))
		       (org-block-begin-line     (:family "NovaMono" :foreground comment))
		       (org-modern-block-name    (:family "NovaMono" :foreground comment))))

 (provide-theme 'my)

