#! /bin/sh

picom -b
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-max --randomize ~/Documents/Wallpapers/* &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#ffffff"
bspc config normal_border_color  "#ffffff"

xmodmap ~/.Xmodmap
